export const listVNSpecialDay = [
    {
        id: 1,
        date: '1/1',
        lunar: false,
        name: 'Tết Dương lịch',
        compensatory: true,
    },
    {
        id: 2,
        date: '30/4',
        lunar: false,
        name: 'Ngày Giải phóng Miền Nam, Thống nhất đất nước',
        compensatory: true,
    },
    {
        id: 3,
        date: '1/5',
        lunar: false,
        name: 'Ngày Quốc tế lao động',
        compensatory: true,
    },
    {
        id: 4,
        date: '2/9',
        lunar: false,
        name: 'Lễ Quốc khánh',
        compensatory: true,
    },
    {
        id: 5,
        date: '10/3',
        lunar: true,
        name: 'Giỗ tổ Hùng Vương',
        compensatory: true,
    },
    {
        id: 6,
        date: '25/12',
        lunar: true,
        name: '25 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 7,
        date: '26/12',
        lunar: true,
        name: '26 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 8,
        date: '27/12',
        lunar: true,
        name: '27 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 9,
        date: '28/12',
        lunar: true,
        name: '28 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 10,
        date: '29/12',
        lunar: true,
        name: '29 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 11,
        date: '30/12',
        lunar: true,
        name: 'Đêm giao thừa',
        compensatory: false,
    },
    {
        id: 12,
        date: '1/1',
        lunar: true,
        name: 'Mùng 1 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 13,
        date: '2/1',
        lunar: true,
        name: 'Mùng 2 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 14,
        date: '3/1',
        lunar: true,
        name: 'Mùng 3 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 15,
        date: '4/1',
        lunar: true,
        name: 'Mùng 4 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 16,
        date: '5/1',
        lunar: true,
        name: 'Mùng 5 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 17,
        date: '6/1',
        lunar: true,
        name: 'Mùng 6 Tết Nguyên Đán',
        compensatory: false,
    },
    {
        id: 18,
        date: '0/0',
        lunar: false,
        name: 'Ngày nghỉ bù',
        compensatory: false,
    },
]
